apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenhat-ai-app
  namespace: backend 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greenhat-ai-app
  template:
    metadata:
      labels:
        app: greenhat-ai-app
    spec:
      containers:
      - name: yolov8
        image: greenhat2registry.azurecr.io/yolov8-demo:13
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: acr-secret
