apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolov8-app
  namespace: default 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolov8-app
  template:
    metadata:
      labels:
        app: yolov8-app
    spec:
      containers:
      - name: yolov8
        image: greenhat2registry.azurecr.io/yolov8-demo:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
