apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenhat-ai-app
  namespace: backend 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greenhat-ai-app
  template:
    metadata:
      labels:
        app: greenhat-ai-app
    spec:
      containers:
      - name: yolov8
        image: greenhat2registry.azurecr.io/yolov8-demo:48
        ports:
        - containerPort: 5000
        env:
        - name: AZURE_CONNECTION_STRING # app.py에서 읽을 환경변수 이름
          valueFrom:
            secretKeyRef:
              name: azure-secret      # 1단계에서 생성한 Secret의 이름
              key: AZURE_CONNECTION_STRING # Secret 안에 있는 데이터의 키(key) 이름
        - name: AZURE_CONTAINER_NAME
          value: "traing-image"     # 원하시는 컨테이너 이름을 여기에 입력
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      imagePullSecrets:
      - name: acr-secret
